"""Bundle cache identity tests; no game engine or arena jobs are required."""
from __future__ import annotations

import copy
import json
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
import tempfile
import threading
import unittest
from unittest.mock import patch

import graph_gauntlet
from arena import payload
from pool_upgrade_state import graph_fingerprint


class GraphBundleIdentityTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        source = self.root / 'source'
        checkpoint = source / 'hazel_runtime' / 'checkpoint'
        checkpoint.mkdir(parents=True)
        (source / 'agent_graph.py').write_text('def agent(obs): return obs\n')
        (source / 'hazel_runtime' / 'logic.py').write_text('RUNTIME = 1\n')
        for file in ('config.json', 'labels.json', 'model.safetensors', 'scaler.npz'):
            (checkpoint / file).write_bytes(f'{file}: reference'.encode())
        self.checkpoint = checkpoint
        self.graph = {'name': 'original', 'turn': {'nodes': [{'id': 'backbone'}]},
                      'source': {'oracle_model_sha256': 'old'},
                      'provenance': {'entrypoint_sha256': 'old',
                                     'runtime_bundle_hashes': {'logic.py': 'old'}}}
        self.run = self.root / 'run'
        self.gauntlet = graph_gauntlet.Gauntlet(self.run, None, opponents=())
        self.pg_patch = patch.object(payload, 'PG', source)
        self.pg_patch.start()
        self.addCleanup(self.pg_patch.stop)

    def bundle_path(self, name):
        return self.run / 'bundles' / name

    def test_matching_legacy_bundle_and_scores_are_reused_with_stale_input_pins(self):
        legacy = 'g_' + graph_fingerprint(self.graph)[:16]
        target = self.bundle_path(legacy)
        payload.write_graph_bundle(target, self.graph, legacy)
        scores = self.run / 'scores'
        scores.mkdir()
        score = scores / f'{legacy}.json'
        self.gauntlet.fingerprint = 'current'
        self.gauntlet.opponent_digests = {'opponent': 'unchanged'}
        score.write_text(json.dumps({'fingerprint': 'current', 'opponents': {'opponent': 'unchanged'},
                                     'margins': {'opponent|1|0': 12.0}}))
        previous_score = score.read_bytes()
        bytecode = target / 'hazel_runtime' / '__pycache__'
        bytecode.mkdir()
        (bytecode / 'logic.cpython-312.pyc').write_bytes(b'generated bytecode')
        old_graph = json.loads((target / 'policy_graph.json').read_text())
        self.assertNotEqual(old_graph['provenance']['runtime_bundle_hashes']['logic.py'], 'old')
        self.assertEqual(old_graph['provenance']['entrypoint_sha256'],
                         payload.sha(payload.PG / 'agent_graph.py'))
        self.assertEqual(self.gauntlet.bundle(copy.deepcopy(self.graph)), legacy)
        self.assertEqual(score.read_bytes(), previous_score)
        self.assertEqual(self.gauntlet._cached(legacy), {'opponent|1|0': 12.0})
        self.assertEqual(sorted(p.name for p in target.parent.iterdir()), [legacy])
        self.assertEqual(self.graph['provenance']['entrypoint_sha256'], 'old')

    def test_changed_checkpoint_or_calibration_never_reuses_old_model_bundle(self):
        old = self.gauntlet.bundle(self.graph)
        self.assertEqual(self.gauntlet.bundle(self.graph), old)
        model = self.checkpoint / 'model.safetensors'
        model.write_bytes(b'new weights')
        newer = self.gauntlet.bundle(self.graph)
        self.assertNotEqual(newer, old)
        self.assertEqual((self.bundle_path(old) / 'hazel_runtime/checkpoint/model.safetensors').read_bytes(),
                         b'model.safetensors: reference')
        calibration = self.checkpoint / 'calibration.json'
        calibration.write_text('{"factor": 1.2}')
        calibrated = self.gauntlet.bundle(self.graph)
        self.assertNotIn(calibrated, (old, newer))
        calibration.write_text('{"factor": 1.3}')
        self.assertNotEqual(self.gauntlet.bundle(self.graph), calibrated)
        calibration.unlink()
        self.assertEqual(self.gauntlet.bundle(self.graph), newer)
        for name, expected in ((old, b'model.safetensors: reference'), (newer, b'new weights')):
            self.assertEqual((self.bundle_path(name) / 'hazel_runtime/checkpoint/model.safetensors').read_bytes(),
                             expected)
        self.assertFalse((self.bundle_path(newer) / 'hazel_runtime/checkpoint/calibration.json').exists())

    def test_config_scaler_labels_and_runtime_bytes_affect_identity(self):
        last = self.gauntlet.bundle(self.graph)
        for file in ('config.json', 'scaler.npz', 'labels.json'):
            path = self.checkpoint / file
            path.write_bytes(path.read_bytes() + b' changed')
            current = self.gauntlet.bundle(self.graph)
            self.assertNotEqual(last, current, file)
            last = current
        runtime = self.checkpoint.parent / 'logic.py'
        runtime.write_text('RUNTIME = 2\n')
        current = self.gauntlet.bundle(self.graph)
        self.assertNotEqual(last, current)
        policy = json.loads((self.bundle_path(current) / 'policy_graph.json').read_text())
        self.assertEqual(policy['provenance']['runtime_bundle_hashes']['logic.py'], payload.sha(runtime))
        self.assertEqual(policy['name'], current)

    def test_damaged_legacy_is_left_intact_and_correct_bundle_is_reused(self):
        legacy = 'g_' + graph_fingerprint(self.graph)[:16]
        target = self.bundle_path(legacy)
        payload.write_graph_bundle(target, self.graph, legacy)
        (target / 'hazel_runtime/checkpoint/model.safetensors').write_bytes(b'stale model')
        name = self.gauntlet.bundle(self.graph)
        self.assertNotEqual(name, legacy)
        self.assertEqual(self.gauntlet.bundle(self.graph), name)
        self.assertEqual((target / 'hazel_runtime/checkpoint/model.safetensors').read_bytes(), b'stale model')

    def test_two_builders_publish_without_touching_each_others_temporary_dirs(self):
        gate = threading.Barrier(2, timeout=10)
        write = payload.write_graph_bundle

        def synchronized_write(*args):
            write(*args)
            gate.wait()

        with patch.object(payload, 'write_graph_bundle', side_effect=synchronized_write):
            with ThreadPoolExecutor(max_workers=2) as pool:
                results = list(pool.map(self.gauntlet.bundle, (self.graph, self.graph)))
        self.assertEqual(results[0], results[1])
        self.assertEqual([p.name for p in self.bundle_path(results[0]).parent.iterdir()], results[:1])
        self.assertTrue((self.bundle_path(results[0]) / 'policy_graph.json').is_file())


if __name__ == '__main__':
    unittest.main()
