#!/usr/bin/env python3
"""Play KAD-MD-24 or KAD-HP-1 against arena opponents on Kaggle CPU notebooks (no GPU quota).

    python3 research/action_diffusion/make_arena.py --checkpoint runs/<run>/best.pt --out <dir>
    kaggle datasets create -p <dir>/dataset        # a later round: kaggle datasets version -p ...
    for k in 1 2 3 4 5; do kaggle kernels push -p <dir>/kernels/$k; done

--variants are model players, NAME=GUIDANCE for KAD-MD-24 (play.Player: 1 = the conditioned model
as trained, > 1 pushes further toward its prompt, a win by the day's top team) or NAME= for a
KAD-HP-1 checkpoint (play.PolicyPlayer, its prompt team). --opponents are names
research/procedural_graph/arena/payload.py knows (the public ladder agents in
shinka/champions/ladder, the replay opponents, hazel, copper, orchard, mohui, ...), plus our
submissions `aspen`, `cedar`, `birch` and `alder` (Aspen Vale, Cedar Ridge, Birch Hollow, Alder
Ford), and a variant's name for self-play. payload.py builds the arena payload
(bundles, arena.py, bundle_agent.py, jobs.json): every pair plays --seeds seeds (the arena's salted
validation seeds) from both seats. This script adds the weights once (the variants' settings.json
point to them), kad_arena.py (arena.py that also keeps every game's replay) and packs it all into
<dir>/dataset/kad_arena_payload.tar, a private dataset. <dir>/kernels/<k> are --shards CPU
notebooks; notebook k plays the jobs whose index is k-1 modulo --shards with 4 workers and writes
results.jsonl (arena.py's lines), traces/ and episodes/ (the replays, for training) to its output.
"""
import argparse
import json
import shutil
import subprocess
import sys
import tarfile
from pathlib import Path

from make_kaggle_kernel import metadata

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
PAYLOAD = REPO / 'research/procedural_graph/arena/payload.py'
SUBMISSIONS = {name: REPO / 'shinka/champions/submissions' / folder for name, folder in (
    ('aspen', 'aspen_vale'), ('cedar', 'cedar_ridge'), ('birch', 'birch_hollow'), ('alder', 'alder_ford'))}
AGENT_FILES = {'play.py': 'play.py', 'model.py': 'model.py', 'policy.py': 'policy.py', 'data.py': 'data.py',
               'arena_main.py': 'main.py'}

LAUNCHER = '''"""KAD arena games, shard {shard} of {shards} (generated by research/action_diffusion/make_arena.py)."""
import os, shutil, subprocess, sys, tarfile
from pathlib import Path

print('CPUs', os.cpu_count(), flush=True)
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', 'kaggle-environments==1.32.7'], check=True)
payload = Path('/tmp/payload')
tars = [p for p in sorted(Path('/kaggle/input').rglob('kad_arena_payload.tar')) if p.is_file()]
if tars:
    with tarfile.open(tars[0]) as tar:
        tar.extractall(payload, filter='data')
else:   # the dataset came unpacked
    jobs = sorted(Path('/kaggle/input').rglob('kad_arena.py'))
    assert jobs, 'no arena payload under /kaggle/input'
    shutil.copytree(jobs[0].parent, payload)
root = next(payload.rglob('kad_arena.py')).parent
out = Path('/kaggle/working')
command = [sys.executable, 'kad_arena.py', '--jobs', 'jobs.json', '--root', '.', '--shard', '{index}',
           '--shards', '{shards}', '--workers', '{workers}', '--out', str(out / 'results.jsonl'),
           '--trace-dir', str(out / 'traces'), '--deadline', '{deadline}']
print('run:', ' '.join(command), flush=True)
code = subprocess.run(command, cwd=root, env=dict(os.environ, KAD_EPISODE_DIR=str(out / 'episodes'))).returncode
print('KAD_ARENA_EXIT=%d' % code, flush=True)
'''


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--checkpoint', required=True)
    ap.add_argument('--out', required=True)
    ap.add_argument('--user', default='sunshinethroughfog')
    ap.add_argument('--slug', default='kaggriculture-kad-arena', help='the dataset; the notebooks are <slug>-<k>')
    ap.add_argument('--eval-id', default='kad-baseline')
    ap.add_argument('--variants', default='kad=1,kadg2=2')
    ap.add_argument('--opponents', default='tetsutani_demand_0927,haideptry_2965_0926,abo_v57,robust_economy,'
                                           'abo_v43,pilkwang_sep,birch')
    ap.add_argument('--seeds', type=int, default=20)
    ap.add_argument('--shards', type=int, default=5)
    ap.add_argument('--workers', type=int, default=4)
    ap.add_argument('--deadline-hours', type=float, default=10.5, help='stop starting games after this')
    args = ap.parse_args()
    out = Path(args.out)
    if out.exists():
        shutil.rmtree(out)
    variants = dict(v.split('=') for v in args.variants.split(','))
    opponents = args.opponents.split(',')
    agents = out / 'agents'
    for name, guidance in variants.items():
        bundle = agents / name
        bundle.mkdir(parents=True)
        for source, target in AGENT_FILES.items():
            shutil.copy2(HERE / source, bundle / target)
        settings = {'checkpoint': '../../weights/best.pt'}
        if guidance:   # KAD-MD-24 only; a KAD-HP-1 variant is NAME= (no guidance)
            settings['guidance'] = float(guidance)
        (bundle / 'settings.json').write_text(json.dumps(settings) + '\n')
    payload = out / 'payload'
    pairs = ','.join(f'{v}:{o}' for v in variants for o in opponents)
    bundles = [f'--bundle={v}={agents / v}' for v in variants]
    bundles += [f'--bundle={name}={SUBMISSIONS[name]}' for name in opponents if name in SUBMISSIONS]
    subprocess.run([sys.executable, str(PAYLOAD), '--eval-id', args.eval_id, '--pairs', pairs, '--seeds',
                    str(args.seeds), '--both-seats', '--out', str(payload), *bundles], check=True)
    (payload / 'weights').mkdir()
    shutil.copy2(args.checkpoint, payload / 'weights' / 'best.pt')
    shutil.copy2(HERE / 'kad_arena.py', payload / 'kad_arena.py')
    dataset = out / 'dataset'
    dataset.mkdir()
    with tarfile.open(dataset / 'kad_arena_payload.tar', 'w') as tar:
        tar.add(payload, arcname='.')
    (dataset / 'dataset-metadata.json').write_text(json.dumps(
        {'title': args.slug, 'id': f'{args.user}/{args.slug}', 'licenses': [{'name': 'other'}]}, indent=2) + '\n')
    for k in range(1, args.shards + 1):
        folder = out / 'kernels' / str(k)
        folder.mkdir(parents=True)
        (folder / 'kad_arena_run.py').write_text(LAUNCHER.format(
            shard=k, shards=args.shards, index=k - 1, workers=args.workers,
            deadline=int(args.deadline_hours * 3600)))
        (folder / 'kernel-metadata.json').write_text(metadata(f'{args.user}/{args.slug}-{k}', 'kad_arena_run.py',
                                                              gpu=False, dataset_sources=[f'{args.user}/{args.slug}']))
    jobs = json.loads((payload / 'jobs.json').read_text())['jobs']
    print(json.dumps({'jobs': len(jobs), 'per_notebook': -(-len(jobs) // args.shards), 'pairs': pairs.split(','),
                      'dataset': str(dataset), 'tar_bytes': (dataset / 'kad_arena_payload.tar').stat().st_size},
                     indent=1))


if __name__ == '__main__':
    main()
