#!/usr/bin/env python3
"""Write the Kaggle kernels that train KAD-MD-24 on 2x T4 (folders for `kaggle kernels push`).

Every day encoded first on CPU notebooks, then training on all of them:

    python3 make_kaggle_kernel.py --prep-parts 5 --out /tmp/kad_prep --user sunshinethroughfog
    for k in 1 2 3 4 5; do kaggle kernels push -p /tmp/kad_prep/$k; done
    # once all five are COMPLETE:
    python3 make_kaggle_kernel.py --data-parts 5 --out /tmp/kad_kernel --user sunshinethroughfog \
        --init-dataset sunshinethroughfog/kaggriculture-action-diffusion-v2-weights
    kaggle kernels push -p /tmp/kad_kernel --accelerator NvidiaTeslaT4

--prep-parts N writes N CPU notebooks, <data-slug>-1..N. Each downloads its share of --days
(split by episode count; Kaggle's day datasets need no credentials), encodes it with every CPU
(train_job.py --extract-only) and saves days/<day>.tar in its output. Kaggle runs at most 5
CPU sessions of an account at once.

The training notebook carries this directory's code (train_job.py, data.py, model.py,
train.py, inference.py) as an embedded tar and finds init.pt (else best.pt) in the attached
--init-dataset (the starting weights: a best.pt, or a last.pt of an earlier run). With
--data-parts N it attaches the outputs of the N data notebooks, unpacks their days into
/tmp/ad/days and runs train_job.py on every day in one round (a day missing there is encoded
before training). Without it, train_job.py downloads and encodes the days itself: the first
--start-days before training, the rest in the background while training runs in rounds of
--round-hours. Either way train.py runs under torchrun on both GPUs until --deadline-hours after
the start (Kaggle stops a session at 12 h). Checkpoints, metrics and logs are written to
/kaggle/working/ad_run, the notebook's output.
"""
import argparse
import base64
import csv
import io
import json
import tarfile
import urllib.request
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
CODE = ('train_job.py', 'data.py', 'model.py', 'train.py', 'inference.py')
INDEX = 'https://www.kaggle.com/api/v1/datasets/download/kaggle/kaggriculture-episodes-index'

LAUNCHER = '''"""KAD-MD-24 action diffusion: every published Kaggriculture day, GPU T4 x2 (generated by
research/action_diffusion/make_kaggle_kernel.py; the code is embedded below)."""
import base64, io, os, shutil, subprocess, sys, tarfile, time
from pathlib import Path

CODE = {code!r}
JOB_ARGS = {job_args!r}
TRAIN_ARGS = {train_args!r}
PREPARED = {prepared!r}   # the days come encoded, as days/<day>.tar in the attached data notebooks' outputs

code = Path('/tmp/ad_code')
code.mkdir(parents=True, exist_ok=True)
with tarfile.open(fileobj=io.BytesIO(base64.b64decode(CODE))) as tar:
    tar.extractall(code)
import torch
gpus = torch.cuda.device_count()
print('torch', torch.__version__, '| GPUs', gpus, [torch.cuda.get_device_name(i) for i in range(gpus)],
      '| CPUs', os.cpu_count(), '| disk free GB', round(shutil.disk_usage('/tmp').free / 1e9, 1), flush=True)
assert gpus >= 2, 'this kernel needs the GPU T4 x2 accelerator'
init = next(p for name in ('init.pt', 'best.pt') for p in sorted(Path('/kaggle/input').rglob(name)))
if PREPARED:
    tars = sorted(Path('/kaggle/input').rglob('days/*.tar'))
    assert tars, 'no prepared days (days/<day>.tar) under /kaggle/input'
    Path('/tmp/ad/days').mkdir(parents=True, exist_ok=True)
    started = time.time()
    for path in tars:
        with tarfile.open(path) as tar:
            tar.extractall('/tmp/ad/days', filter='data')
    print('unpacked %d prepared days, %.1f GB, in %.0f s' % (
        len(tars), sum(p.stat().st_size for p in tars) / 1e9, time.time() - started), flush=True)
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', 'orjson'])
out = Path('/kaggle/working')
command = [sys.executable, str(code / 'train_job.py'), '--root', '/tmp/ad', '--run-dir', str(out / 'ad_run'),
           '--gpus', str(gpus), '--init-from', str(init), *JOB_ARGS, '--', *TRAIN_ARGS]
print('job:', ' '.join(command), flush=True)
exit_code = subprocess.run(command, cwd=code).returncode
for name in ('extract.log', 'current/manifest.json'):
    if Path('/tmp/ad', name).exists():
        shutil.copy(Path('/tmp/ad', name), out / ('data_' + name.replace('/', '_')))
print('KAGGLE_TRAIN_EXIT=%d' % exit_code, flush=True)
'''

PREP_LAUNCHER = '''"""KAD-MD-24 training data: encode Kaggriculture days on a CPU notebook (generated by
research/action_diffusion/make_kaggle_kernel.py; the code is embedded below). Its output,
days/<day>.tar (<day>/manifest.json, train/, val/), is an input of the training notebook."""
import base64, io, os, shutil, subprocess, sys, tarfile
from pathlib import Path

CODE = {code!r}
DAYS = {days!r}

code = Path('/tmp/ad_code')
code.mkdir(parents=True, exist_ok=True)
with tarfile.open(fileobj=io.BytesIO(base64.b64decode(CODE))) as tar:
    tar.extractall(code)
workers = len(os.sched_getaffinity(0))
print('CPUs', workers, '| disk free GB', round(shutil.disk_usage('/tmp').free / 1e9, 1), '| days', len(DAYS),
      flush=True)
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', 'orjson'])
root, out = Path('/tmp/ad'), Path('/kaggle/working/days')
out.mkdir(parents=True, exist_ok=True)
missing = []
for day in DAYS:   # one day at a time, packed as soon as it is encoded
    subprocess.run([sys.executable, str(code / 'train_job.py'), '--root', str(root), '--extract-only',
                    '--days', day, '--workers', str(workers)], cwd=code)
    folder = root / 'days' / day
    if not (folder / 'manifest.json').exists():
        missing.append(day)
        continue
    with tarfile.open(out / (day + '.tar'), 'w') as tar:
        tar.add(folder, arcname=day)
    shutil.rmtree(folder)
    print('PREP_PACKED %s %.2f GB' % (day, (out / (day + '.tar')).stat().st_size / 1e9), flush=True)
print('PREP_DONE %d/%d days, %.2f GB; missing %s' % (
    len(DAYS) - len(missing), len(DAYS), sum(p.stat().st_size for p in out.glob('*.tar')) / 1e9, missing),
    flush=True)
'''


def code_archive():
    buffer = io.BytesIO()
    with tarfile.open(fileobj=buffer, mode='w:gz') as tar:
        for name in CODE:
            tar.add(HERE / name, arcname=name)
    return base64.b64encode(buffer.getvalue()).decode()


def index_rows():
    """Kaggle's index of the published days (date, episode_count, ...), newest first."""
    with urllib.request.urlopen(INDEX, timeout=120) as response:
        archive = zipfile.ZipFile(io.BytesIO(response.read()))
    rows = list(csv.DictReader(io.TextIOWrapper(archive.open('manifest.csv'), encoding='utf-8')))
    return sorted(rows, key=lambda r: r['date'], reverse=True)


def select_days(spec, rows):
    """--days (all, last:N or a comma list of YYYY-MM-DD) as index rows, newest first."""
    if spec == 'all':
        return rows
    if spec.startswith('last:'):
        return rows[:int(spec.split(':', 1)[1])]
    wanted = {d.strip() for d in spec.split(',') if d.strip()}
    missing = wanted - {r['date'] for r in rows}
    if missing:
        raise SystemExit(f'not in the episodes index: {sorted(missing)}')
    return [r for r in rows if r['date'] in wanted]


def split_days(rows, parts):
    """The days in `parts` groups of about equal episode counts (each day, largest first, goes to
    the lightest group), each group newest first."""
    groups = [[0, k, []] for k in range(parts)]
    for row in sorted(rows, key=lambda r: -int(r['episode_count'])):
        group = min(groups)
        group[0] += int(row['episode_count'])
        group[2].append(row['date'])
    return [sorted(days, reverse=True) for _, _, days in sorted(groups, key=lambda g: g[1])]


def metadata(kernel_id, code_file, gpu, dataset_sources=(), kernel_sources=()):
    meta = {'id': kernel_id, 'title': kernel_id.split('/', 1)[1], 'code_file': code_file,
            'language': 'python', 'kernel_type': 'script', 'is_private': 'true',
            'enable_gpu': 'true' if gpu else 'false', 'enable_tpu': 'false', 'enable_internet': 'true',
            'dataset_sources': list(dataset_sources), 'competition_sources': [],
            'kernel_sources': list(kernel_sources)}
    if gpu:
        meta['machine_shape'] = 'NvidiaTeslaT4'
    return json.dumps(meta, indent=2) + '\n'


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--out', required=True, help='kernel folder to write (--prep-parts: a subfolder per part)')
    ap.add_argument('--user', required=True, help='Kaggle user that owns the kernels')
    ap.add_argument('--slug', default='kaggriculture-action-diffusion-all', help='the training notebook')
    ap.add_argument('--data-slug', default='kaggriculture-action-diffusion-data',
                    help='the data notebooks are <data-slug>-1..N')
    ap.add_argument('--prep-parts', type=int, default=0, help='write this many data notebooks instead')
    ap.add_argument('--data-parts', type=int, default=0,
                    help='train on the days encoded by this many data notebooks (attached as inputs)')
    ap.add_argument('--init-dataset', help='dataset holding init.pt or best.pt (owner/slug); required for training')
    ap.add_argument('--days', default='all', help='all, last:N or a comma list of YYYY-MM-DD')
    ap.add_argument('--start-days', type=int, default=4, help='without --data-parts: days encoded before training')
    ap.add_argument('--background-workers', type=int, default=3,
                    help='without --data-parts: niced encoders of the other days while training runs')
    ap.add_argument('--round-hours', type=float, default=1.0,
                    help='without --data-parts: training restarts this often to take new days')
    ap.add_argument('--deadline-hours', type=float, default=11.3)
    ap.add_argument('--train-args', default='--batch-size 64 --lr 3e-4 --workers 1 --buffer-files 24 '
                                            '--eval-every 5000 --save-every-min 10 --rating-halving 50 --margin-doubling 0.1 '
                                            '--recency-halving 14')
    args = ap.parse_args()
    out = Path(args.out)
    code = code_archive()
    if args.prep_parts:
        rows = select_days(args.days, index_rows())
        counts = {r['date']: int(r['episode_count']) for r in rows}
        for k, days in enumerate(split_days(rows, args.prep_parts), 1):
            folder = out / str(k)
            folder.mkdir(parents=True, exist_ok=True)
            (folder / 'kaggle_prep.py').write_text(PREP_LAUNCHER.format(code=code, days=days))
            (folder / 'kernel-metadata.json').write_text(
                metadata(f'{args.user}/{args.data_slug}-{k}', 'kaggle_prep.py', gpu=False))
            print(f'wrote {folder}: {len(days)} days, {sum(counts[d] for d in days)} episodes ({days[-1]}..{days[0]})')
        return
    if not args.init_dataset:
        ap.error('--init-dataset is required for the training notebook')
    if args.data_parts:
        days = [r['date'] for r in select_days(args.days, index_rows())]
        job_args = ['--days', ','.join(days), '--start-days', str(len(days)), '--val-days', '1',
                    '--round-hours', str(args.deadline_hours), '--deadline-hours', str(args.deadline_hours)]
        sources = [f'{args.user}/{args.data_slug}-{k}' for k in range(1, args.data_parts + 1)]
    else:
        job_args = ['--days', args.days, '--start-days', str(args.start_days), '--val-days', '1',
                    '--background-workers', str(args.background_workers),
                    '--round-hours', str(args.round_hours), '--deadline-hours', str(args.deadline_hours)]
        sources = []
    out.mkdir(parents=True, exist_ok=True)
    (out / 'kaggle_train.py').write_text(LAUNCHER.format(code=code, job_args=job_args,
                                                         train_args=args.train_args.split(),
                                                         prepared=bool(args.data_parts)))
    (out / 'kernel-metadata.json').write_text(metadata(f'{args.user}/{args.slug}', 'kaggle_train.py', gpu=True,
                                                       dataset_sources=[args.init_dataset],
                                                       kernel_sources=sources))
    print(f'wrote {out}/kaggle_train.py ({(out / "kaggle_train.py").stat().st_size / 1e3:.0f} kB) and '
          f'kernel-metadata.json' + (f'; {len(days)} prepared days from {len(sources)} data notebooks'
                                     if args.data_parts else ''))


if __name__ == '__main__':
    main()
