#!/usr/bin/env python3
"""Write the Kaggle kernel that trains KAD-MD-24 on 2x T4 (a folder for `kaggle kernels push`).

    python3 make_kaggle_kernel.py --out /tmp/kad_kernel --user sunshinethroughfog \
        --init-dataset sunshinethroughfog/kaggriculture-action-diffusion-init
    kaggle kernels push -p /tmp/kad_kernel --accelerator NvidiaTeslaT4

The kernel script carries this directory's code (train_job.py, data.py, model.py, train.py,
inference.py) as an embedded tar, finds init.pt (else best.pt) in the attached --init-dataset
(the starting weights: a best.pt, or a last.pt of an earlier run), and runs
train_job.py: every published day newest first (downloaded inside the notebook, no
credentials needed), the first --start-days encoded before training, the rest in the
background, train.py under torchrun on both GPUs in rounds, all ending --deadline-hours after
the start (Kaggle stops a session at 12 h). Checkpoints, metrics and logs are written to
/kaggle/working/ad_run, the notebook's output; the encoded data stays in /tmp.
"""
import argparse
import base64
import io
import json
import tarfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
CODE = ('train_job.py', 'data.py', 'model.py', 'train.py', 'inference.py')

LAUNCHER = '''"""KAD-MD-24 action diffusion: every published Kaggriculture day, GPU T4 x2 (generated by
research/action_diffusion/make_kaggle_kernel.py; the code is embedded below)."""
import base64, io, os, shutil, subprocess, sys, tarfile, time
from pathlib import Path

CODE = {code!r}
JOB_ARGS = {job_args!r}
TRAIN_ARGS = {train_args!r}

code = Path('/tmp/ad_code')
code.mkdir(parents=True, exist_ok=True)
with tarfile.open(fileobj=io.BytesIO(base64.b64decode(CODE))) as tar:
    tar.extractall(code)
import torch
gpus = torch.cuda.device_count()
print('torch', torch.__version__, '| GPUs', gpus, [torch.cuda.get_device_name(i) for i in range(gpus)],
      '| CPUs', os.cpu_count(), '| disk free GB', round(shutil.disk_usage('/tmp').free / 1e9, 1), flush=True)
assert gpus >= 2, 'this kernel needs the GPU T4 x2 accelerator'
init = next(p for name in ('init.pt', 'best.pt') for p in sorted(Path('/kaggle/input').rglob(name)))
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', 'orjson'])
out = Path('/kaggle/working')
command = [sys.executable, str(code / 'train_job.py'), '--root', '/tmp/ad', '--run-dir', str(out / 'ad_run'),
           '--gpus', str(gpus), '--init-from', str(init), *JOB_ARGS, '--', *TRAIN_ARGS]
print('job:', ' '.join(command), flush=True)
exit_code = subprocess.run(command, cwd=code).returncode
for name in ('extract.log', 'current/manifest.json'):
    if Path('/tmp/ad', name).exists():
        shutil.copy(Path('/tmp/ad', name), out / ('data_' + name.replace('/', '_')))
print('KAGGLE_TRAIN_EXIT=%d' % exit_code, flush=True)
'''


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--out', required=True, help='kernel folder to write')
    ap.add_argument('--user', required=True, help='Kaggle user that owns the kernel')
    ap.add_argument('--slug', default='kaggriculture-action-diffusion-all')
    ap.add_argument('--init-dataset', required=True, help='dataset holding init.pt or best.pt (owner/slug)')
    ap.add_argument('--days', default='all')
    ap.add_argument('--start-days', type=int, default=4)
    ap.add_argument('--background-workers', type=int, default=3,
                    help='niced encoders of the other days while training runs (they take only idle CPU)')
    ap.add_argument('--round-hours', type=float, default=1.0, help='training restarts this often to take new days')
    ap.add_argument('--deadline-hours', type=float, default=11.3)
    ap.add_argument('--train-args', default='--batch-size 64 --lr 3e-4 --workers 1 --buffer-files 24 '
                                            '--eval-every 5000 --save-every-min 10 --rating-halving 50 --margin-doubling 0.1')
    args = ap.parse_args()
    buffer = io.BytesIO()
    with tarfile.open(fileobj=buffer, mode='w:gz') as tar:
        for name in CODE:
            tar.add(HERE / name, arcname=name)
    job_args = ['--days', args.days, '--start-days', str(args.start_days), '--val-days', '1',
                '--background-workers', str(args.background_workers),
                '--round-hours', str(args.round_hours), '--deadline-hours', str(args.deadline_hours)]
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    (out / 'kaggle_train.py').write_text(LAUNCHER.format(code=base64.b64encode(buffer.getvalue()).decode(),
                                                         job_args=job_args, train_args=args.train_args.split()))
    (out / 'kernel-metadata.json').write_text(json.dumps({
        'id': f'{args.user}/{args.slug}', 'title': args.slug, 'code_file': 'kaggle_train.py',
        'language': 'python', 'kernel_type': 'script', 'is_private': 'true', 'enable_gpu': 'true',
        'enable_tpu': 'false', 'enable_internet': 'true', 'machine_shape': 'NvidiaTeslaT4',
        'dataset_sources': [args.init_dataset], 'competition_sources': [], 'kernel_sources': []}, indent=2) + '\n')
    print(f'wrote {out}/kaggle_train.py ({(out / "kaggle_train.py").stat().st_size / 1e3:.0f} kB) and kernel-metadata.json')


if __name__ == '__main__':
    main()
